### PR TITLE
Unit test

### PR DESCRIPTION
**Pull request by Olthoff231381**
Added the first unit test.
Checked that both an empty and a filled dir are detected properly

### CODE REVIEW

**Review by iulusoy — CHANGES_REQUESTED** [review]
looks good already! 
I would add some more tests: 
- if the directory does not contain eml or html files (the list is empty), the function `list_of_files` should throw an exception (for example, a `RunTimeError`, or maybe you [find a better one](https://docs.python.org/3/library/exceptions.html)
- the directory does not exist - here we again need an exception in the original function
- a test that the list only contains eml or html files

**Review by Olthoff231381 — COMMENTED** [review]
I would include the additional tests with the push for #21

**Comment by Olthoff231381** [comment]
Can I merge this branch?

**Comment by iulusoy** [comment]
Ah ok , you want to include the exceptions in the new branch with better test coverage. Ok sure.

**Review by iulusoy — APPROVED** [review]

**Pull request merged**
